# Generated by Django 6.0.2 on 2026-03-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payment_payment_status_payment_stripe_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на оплату в Stripe'),
        ),
    ]
